"""
grg_autolearner.py — Auto-Learning System for Grg AI
Consolidates cached Q&A pairs into organized Knowledge .md files.
When idle, groups cached answers by topic and creates .md files for RAG.
"""

import os
import re
import json
import time
from collections import defaultdict
from datetime import datetime

_TOPIC_KEYWORDS = {
    "python": ["python", "pip", "django", "flask", "fastapi", "pandas", "numpy", "pytest"],
    "javascript": ["javascript", "js", "node", "npm", "react", "vue", "angular", "typescript", "ts"],
    "databases": ["sql", "database", "postgres", "mysql", "mongo", "redis", "query", "table", "index"],
    "web_development": ["html", "css", "http", "api", "rest", "cors", "fetch", "dom", "browser"],
    "devops": ["docker", "kubernetes", "k8s", "nginx", "deploy", "ci/cd", "github actions", "linux"],
    "git": ["git", "commit", "branch", "merge", "rebase", "pull", "push", "clone"],
    "algorithms": ["algorithm", "sort", "search", "tree", "graph", "dynamic programming", "recursion", "big o"],
    "security": ["security", "xss", "csrf", "sql injection", "password", "encrypt", "auth", "jwt", "token"],
    "networking": ["tcp", "udp", "dns", "http", "websocket", "ip", "port", "ssl", "tls"],
    "general_programming": ["function", "class", "variable", "loop", "array", "object", "error", "debug"],
}

MIN_ENTRIES_PER_TOPIC = 3
PROCESSED_MARKER = "grg_autolearner_processed.json"


class AutoLearner:
    def __init__(self, knowledge_dir="Knowledge", cache=None):
        self.knowledge_dir = knowledge_dir
        self.cache = cache
        self.processed_file = os.path.join(knowledge_dir, PROCESSED_MARKER)
        self.processed_hashes = self._load_processed()

    def _load_processed(self):
        if not os.path.exists(self.processed_file):
            return set()
        try:
            with open(self.processed_file, "r") as f:
                return set(json.load(f))
        except Exception:
            return set()

    def _save_processed(self):
        os.makedirs(self.knowledge_dir, exist_ok=True)
        try:
            with open(self.processed_file, "w") as f:
                json.dump(list(self.processed_hashes), f)
        except Exception:
            pass

    def _detect_topic(self, question, answer):
        text = (question + " " + answer).lower()
        scores = {}
        for topic, keywords in _TOPIC_KEYWORDS.items():
            score = sum(1 for kw in keywords if kw in text)
            if score > 0:
                scores[topic] = score
        if not scores:
            return "general_programming"
        return max(scores, key=scores.get)

    def _group_by_topic(self, entries):
        groups = defaultdict(list)
        for entry in entries:
            entry_hash = entry.get("hash", "")
            if entry_hash in self.processed_hashes:
                continue
            topic = self._detect_topic(entry["question"], entry["answer"])
            groups[topic].append(entry)
        return dict(groups)

    def _generate_knowledge_md(self, topic, entries):
        title = topic.replace("_", " ").title()
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        lines = [
            "# " + title + " — Auto-Learned Knowledge",
            "",
            "*Auto-generated by Grg AI Auto-Learner on " + timestamp + "*",
            "*Source: " + str(len(entries)) + " cached conversations*",
            "",
            "---",
            "",
        ]
        for i, entry in enumerate(entries, 1):
            question = entry.get("question", "").strip()
            answer = entry.get("answer", "").strip()
            if not question or not answer:
                continue
            lines.append("## Q" + str(i) + ": " + question)
            lines.append("")
            lines.append(answer)
            lines.append("")
            lines.append("---")
            lines.append("")
        return "\n".join(lines)

    def consolidate(self):
        if self.cache is None:
            return {"error": "No cache provided"}
        entries = self.cache.get_all_entries()
        if not entries:
            return {"status": "nothing_to_process", "entries": 0}
        groups = self._group_by_topic(entries)
        if not groups:
            return {"status": "nothing_new", "entries": 0}
        os.makedirs(self.knowledge_dir, exist_ok=True)
        stats = {"topics_processed": 0, "entries_processed": 0, "files_created": []}

        for topic, topic_entries in groups.items():
            if len(topic_entries) < MIN_ENTRIES_PER_TOPIC:
                continue
            md_content = self._generate_knowledge_md(topic, topic_entries)
            filename = "learned_" + topic + ".md"
            filepath = os.path.join(self.knowledge_dir, filename)
            if os.path.exists(filepath):
                with open(filepath, "r", encoding="utf-8") as f:
                    existing = f.read()
                md_content = existing.rstrip() + "\n\n" + md_content
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(md_content)
            for entry in topic_entries:
                self.processed_hashes.add(entry.get("hash", ""))
            stats["topics_processed"] += 1
            stats["entries_processed"] += len(topic_entries)
            stats["files_created"].append(filename)

        self._save_processed()
        stats["status"] = "consolidated"
        return stats

    def get_learning_stats(self):
        learned_files = []
        if os.path.exists(self.knowledge_dir):
            learned_files = [f for f in os.listdir(self.knowledge_dir) if f.startswith("learned_") and f.endswith(".md")]
        total_lines = 0
        for f in learned_files:
            try:
                with open(os.path.join(self.knowledge_dir, f), "r") as fh:
                    total_lines += len(fh.readlines())
            except Exception:
                pass
        return {
            "learned_files": len(learned_files),
            "files": learned_files,
            "total_lines": total_lines,
            "processed_entries": len(self.processed_hashes),
        }
